prooph_event_store:
    stores:
        todo_store:
            event_store: Prooph\EventStore\Pdo\MySqlEventStore
            repositories:
                todo_list:
                    repository_class: Prooph\ProophessorDo\Infrastructure\Repository\EventStoreTodoList
                    aggregate_type: Prooph\ProophessorDo\Model\Todo\Todo
                    aggregate_translator: prooph_event_sourcing.aggregate_translator

                user_collection:
                    repository_class: Prooph\ProophessorDo\Infrastructure\Repository\EventStoreUserCollection
                    aggregate_type: Prooph\ProophessorDo\Model\User\User
                    aggregate_translator: prooph_event_sourcing.aggregate_translator
    projection_managers:
        todo_projection_manager:
            event_store: Prooph\EventStore\Pdo\MySqlEventStore # event store
            connection: 'doctrine.pdo.connection'
            projections:
                user_projection:
                    read_model: Prooph\ProophessorDo\Projection\User\UserReadModel
                    projection: Prooph\ProophessorDo\Projection\User\UserProjection
                todo_projection:
                    read_model: Prooph\ProophessorDo\Projection\Todo\TodoReadModel
                    projection: Prooph\ProophessorDo\Projection\Todo\TodoProjection
                todo_reminder_projection:
                    read_model: Prooph\ProophessorDo\Projection\Todo\TodoReminderReadModel
                    projection: Prooph\ProophessorDo\Projection\Todo\TodoReminderProjection


services:
    Prooph\EventStore\Pdo\MySqlEventStore:
        arguments: ['@prooph_event_store.message_factory', '@doctrine.pdo.connection', '@prooph_event_store.single_stream_strategy']

    doctrine.pdo.connection:
        class: PDO
        factory: ['@database_connection', getWrappedConnection]

    prooph_event_store.single_stream_strategy:
        class: Prooph\EventStore\Pdo\PersistenceStrategy\MySqlSingleStreamStrategy

    prooph_event_sourcing.aggregate_translator:
        class: Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator